[project]
name = "fastapi-guide"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "python-multipart>=0.0.20",
    "uvicorn>=0.34.3",
]
